services:
  qwen3-8b:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        HF_TOKEN: ${HF_TOKEN}
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - count: all              #  ← дефис ОБЯЗАТЕЛЕН!
              capabilities: ["gpu"]   #  ← и это в том же блоке

    command: >
      --model Qwen/Qwen3-8B
      --dtype float16
      --tensor-parallel-size 1
      --enable-chunked-prefill False
      --max-model-len 32768
      --port 5080
    environment:
      - HF_TOKEN=${HF_TOKEN}
    shm_size: "16g"
    volumes:
      - models:/root/.cache/huggingface
    ports:
      - "5080:5080"

volumes:
  models:
